### ISSUE TITLE
Leap Motion connection problems in Wine

### ISSUE THREAD

**Issue by vivi90** [emilianavt/OpenSeeFace#17]
Because there is no repository for VSeeFace, i decided to write it here.

I am using Linux (Manjaro) so i am running VSeeFace in Wine in combination with OpenSeeFace.
That works great, thank you so much :-)

But now i wanted to add the Leap Motion sensor.
I have managed to run the Leap Motion SDK and everything seems to work fine there.
But i am not able to get it work in VSeeFace :-(
So how does VSeeFace connect to the Leap Motion sensor?

Because VSeeFace is created with Unity, is it possible to get an Linux build of it?
Would help a lot, i think.

**Comment by emilianavt** [comment]
VSeeFace uses the Leap Motion V4 SDK. I believe only the V2 one is available for Linux, so unless it's possible to run that through wine as well, it may not work. VSeeFace uses a bunch of WinAPI calls for things like hotkeys, it would need new camera reading code to properly support device capability enumeration and there is no Linux version of OVRLipSync, so a Linux build would have quite reduced functionality and then there's the incompatibility with the up to date Leap Motion SDK. Until there are good solutions for the last points, I don't think it's really worth working on when most of the functionality works through wine.

**Comment by vivi90** [comment]
> VSeeFace uses a bunch of WinAPI calls for things like hotkeys, it would need new camera reading code to properly support device capability enumeration 

I think that's no problem to manage that.

> and there is no Linux version of OVRLipSync

I am also not sure if there is an alternative way.

> and then there's the incompatibility with the up to date Leap Motion SDK. 

Hm, how about to include backward compatibility for the old Leap Motion SDK?

> Until there are good solutions for the last points, I don't think it's really worth working on when most of the functionality works through wine.

Yes, for now.
It would help a lot if you would make it open source.
I know you are using paid Assets but maybe they are replaceable by free ones?

**Comment by emilianavt** [comment]
> Hm, how about to include backward compatibility for the old Leap Motion SDK?

I'm not aware of any way to do this.

> It would help a lot if you would make it open source.
> I know you are using paid Assets but maybe they are replaceable by free ones?

Splitting the repository to use different assets or even just leaving them out would be too annoying for me to want to deal with and to be quite frank, I simply don't want to make it open source. All the hard parts are already open and would just need a new UI layer wrapped around them. The [OpenSeeFaceSample](https://github.com/emilianavt/OpenSeeFaceSample) repository already contains a working project with a basic setup that works on Linux. Depending on how different the V2 API is, you may be able to simply use the [hand tracking code](https://gist.github.com/emilianavt/b211073096a4484fb92e6550212c2f48) as well.

The IK quality on OpenSeeFaceSample is lower, but that's simply because there's no free equivalent to Final IK's VRIK.

**Comment by vivi90** [comment]
> The [OpenSeeFaceSample](https://github.com/emilianavt/OpenSeeFaceSample) repository already contains a working project with a basic setup that works on Linux. Depending on how different the V2 API is, you may be able to simply use the [hand tracking code](https://gist.github.com/emilianavt/b211073096a4484fb92e6550212c2f48) as well.

Oh, i was not aware of this repository, thanks :-)
