### ISSUE TITLE
landmark losss problem

### ISSUE THREAD

**Issue by yutaka329** [emilianavt/OpenSeeFace#24]
nice work,  I dont  comprehend heatmap offset format.  such as  x_offset= 223 * log(p/(1-p)) / 16.
can you provide some  explanation?   thank you.

**Comment by emilianavt** [comment]
Hi!

Offset values are in the range [0, 1), normalized with respect to the full resolution of the image. However, during training, the model was not able to learn offsets very well, because the differences from pixel to pixel were very slight. To make the differences stronger and offsets easier to learn, when creating the offset maps for training, I multiply offsets by 16 and take the sigmoid to bring them back into the range of [0, 1). `log(p/(1-p)) / 16` is the inverse of multiplying by 16 and taking the sigmoid.

I hope that helps a bit. If you have any further questions, please let me know.

**Comment by yutaka329** [comment]
got it , thank you a lot for your reply
