### ISSUE TITLE
socket.io support

### ISSUE THREAD

**Issue by NexusNull** [emilianavt/OpenSeeFace#28]
I would like to serve the tracking data using a socket.io server so that it's easy to access the data from a browser. I'm already working an a prototype but I would like to know if that is something that you would be interested in. If you are, I'd give it the appropriate polish and make a pull request.

**Comment by emilianavt** [comment]
That does in fact sound interesting!

**Comment by NexusNull** [comment]
Alright, I'm a bit busy now but i'll get it out as soon as possible.

**Comment by CousinZe** [comment]
According to my personal experience, socket.io clients, despite the JavaScript version, are either of poor quality or only supports very specific version of socket.io protocol. IMHO Since websocket is now widely supported by both browsers and middlewares, such "custom" protocols should be deprecated.
