### ISSUE TITLE
randomly black out when ir tracking (lenovo 500)

### ISSUE THREAD

**Issue by Nariri** [emilianavt/OpenSeeFace#61]
I tried many arguments and rebuild few times, but it didn't solved.
When I turn on ir in obs that works correctly (not blacked out, exactly it repeatly blinked like incandescent light)
on OSF, not blinked at all and blacked out randomly.
idk what parts having trouble, but different of obs and osf can tell somehing I think. 

under txt file is short log of excuting (no arguments applied without -c (grabbing ir cam))

[lenovo500irlog.txt](https://github.com/emilianavt/OpenSeeFace/files/12241608/lenovo500irlog.txt)

**Comment by emilianavt2** [comment]
Perhaps the issue is that's an IR camera? OpenSeeFace was only trained on regular color RGB images. However, if the image actually blanks out, it might be some other issue. Have you set the exact same camera settings in OBS and OSF (resolution, frame rate, color space) and made sure that no other application is accessing the camera while OSF is running?

**Comment by D337z** [comment]
If I may chime in, the issue may be with the brightness adjustment.  When an IR camera comes on, it reflects light onto the subject and then the sensor collects what light comes back and processes it as an image.  However, that image may not be properly processed to reduce brightness and make up for the level of IR light in the room.
OBS may automatically adjust the image so that it can be viewed in black and white while other programs, such as OpenSeeFace, may not.  It may be a round-about way of achieving this, but try adding the camera as an input for your scenes that is not viewed and then output its corrected data from OBS to OpenSeeFace or another program via the Virtual Webcam feature.  If this fixes the issue, then it is verified as being the cause.
Also, you may like to wipe your eyelids with something to remove any oils that may reflect the IR light as it will be difficult to sense open and closed eyes in such a manner.

Also note:  Most IR camera sensors have a MUCH lower resolution than the normal webcam counterpart.
